apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pleesah-havnesjef
  namespace: leesah
spec:
  filesFrom:
    - secret: pleesah-havnesjef
      mountPath: /var/run/secrets/havnesjef
    - secret: pleesah-havnesjef
      mountPath: /var/run/configmaps/havnesjef
  ingresses:
    - https://pleesah.ansatt.nav.no

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pleesah-havnesjef
  namespace: leesah
spec:
  podSelector:
    matchLabels:
      app: pleesah-havnesjef
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 34.88.113.215/32
    ports:
    - protocol: TCP
      port: 443

